"""add_users.name_column

Revision ID: 988c93187aae
Revises: ffdc0a98111c
Create Date: 2021-06-02 15:48:29.446706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988c93187aae'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
