"""changed the stroke count column

Revision ID: 0e432a6642ac
Revises: 6ff180cb06cf
Create Date: 2021-06-03 00:54:47.518755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e432a6642ac'
down_revision = '6ff180cb06cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'strokeCount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'strokeCount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
