"""fixed missing columns issue

Revision ID: 6ff180cb06cf
Revises: 7fd13fd2a899
Create Date: 2021-06-02 23:52:08.529904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff180cb06cf'
down_revision = '7fd13fd2a899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('grade', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('jlpt', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('kunReadings', sa.String(length=750), nullable=True))
    op.add_column('characters', sa.Column('meanings', sa.String(length=750), nullable=True))
    op.add_column('characters', sa.Column('nameReadings', sa.String(length=750), nullable=True))
    op.add_column('characters', sa.Column('onReadings', sa.String(length=750), nullable=True))
    op.add_column('characters', sa.Column('strokeCount', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('unicode', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'unicode')
    op.drop_column('characters', 'strokeCount')
    op.drop_column('characters', 'onReadings')
    op.drop_column('characters', 'nameReadings')
    op.drop_column('characters', 'meanings')
    op.drop_column('characters', 'kunReadings')
    op.drop_column('characters', 'jlpt')
    op.drop_column('characters', 'grade')
    # ### end Alembic commands ###
