"""add decks, characters and all of the relationships associated between those two tables and users

Revision ID: 7fd13fd2a899
Revises: 988c93187aae
Create Date: 2021-06-02 23:43:37.060341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd13fd2a899'
down_revision = '988c93187aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kanjiCharacter', sa.String(length=20), nullable=False),
    sa.Column('heisigEn', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deckName', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('usersId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usersId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_characters',
    sa.Column('usersId', sa.Integer(), nullable=False),
    sa.Column('charactersId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charactersId'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['usersId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('usersId', 'charactersId')
    )
    op.create_table('decks_characters',
    sa.Column('decksId', sa.Integer(), nullable=False),
    sa.Column('charactersId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charactersId'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['decksId'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('decksId', 'charactersId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decks_characters')
    op.drop_table('users_characters')
    op.drop_table('decks')
    op.drop_table('characters')
    # ### end Alembic commands ###
